# Generated by Django 4.2.28 on 2026-02-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('schema', models.JSONField(help_text='Estrutura JSON do dashboard (blocos, gráficos, etc.)', verbose_name='Schema')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Template de Dashboard',
                'verbose_name_plural': 'Templates de Dashboards',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome único para identificar a fonte de dados', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('sql', models.TextField(help_text='Query SQL (apenas SELECT). Use %(param)s para parâmetros.', verbose_name='Query SQL')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DashboardInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='dashboards.dashboardtemplate', verbose_name='Template')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.unidade', verbose_name='Unidade')),
                ('usuarios_com_acesso', models.ManyToManyField(blank=True, related_name='dashboards_acessiveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuários com Acesso')),
            ],
            options={
                'verbose_name': 'Instância de Dashboard',
                'verbose_name_plural': 'Instâncias de Dashboards',
                'ordering': ['-criado_em'],
                'unique_together': {('template', 'unidade')},
            },
        ),
    ]
