# Generated by Django 4.2.28 on 2026-02-15 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome identificador da conexão', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('host', models.CharField(help_text='Endereço do servidor (ex: localhost, 192.168.1.10)', max_length=255, verbose_name='Host')),
                ('porta', models.IntegerField(default=5432, help_text='Porta do PostgreSQL (padrão: 5432)', verbose_name='Porta')),
                ('database', models.CharField(help_text='Nome do banco de dados', max_length=100, verbose_name='Database')),
                ('usuario', models.CharField(help_text='Usuário para autenticação', max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(help_text='Senha do usuário (armazenada de forma segura)', max_length=255, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Conexão ao banco de dados onde a query será executada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasources', to='dashboards.connection', verbose_name='Conexão'),
        ),
    ]
