# Generated by Django 4.2.28 on 2026-02-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_connection_datasource_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardinstance',
            name='filtro_sql',
            field=models.TextField(blank=True, help_text="Cláusula WHERE customizada (ex: unidade_codigo = 'SP-01' OR status = 'ativo')", verbose_name='Filtro SQL'),
        ),
    ]
