# Generated by Django 4.2.28 on 2026-02-15 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_dashboardinstance_filtro_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Identificador do tipo (ex: bar-chart, line-chart, pie-chart)', max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componentes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome identificador do componente no template', max_length=100, verbose_name='Nome')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do componente (cores, labels, eixos, etc)', verbose_name='Configurações')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do componente no dashboard', verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='dashboards.componenttype', verbose_name='Tipo de Componente')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='dashboards.datasource', verbose_name='Fonte de Dados')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='dashboards.dashboardtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Componente do Template',
                'verbose_name_plural': 'Componentes dos Templates',
                'ordering': ['template', 'ordem', 'nome'],
                'unique_together': {('template', 'nome')},
            },
        ),
    ]
