# Generated by Django 4.2.28 on 2026-02-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_componenttype_templatecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtemplate',
            name='schema',
            field=models.JSONField(blank=True, help_text='Estrutura JSON do dashboard (blocos, gráficos, etc.) - Opcional', null=True, verbose_name='Schema'),
        ),
    ]
