# Generated by Django 4.2.28 on 2026-02-15 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_dashboardtemplate_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Título exibido no bloco (ex: 'Vendas por dia', 'Top 10 produtos')", max_length=200, verbose_name='Título')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição do bloco no dashboard (menor número = primeiro)', verbose_name='Ordem')),
                ('chart_type', models.CharField(choices=[('bar', 'Gráfico de Barras'), ('line', 'Gráfico de Linhas'), ('pie', 'Gráfico de Pizza'), ('area', 'Gráfico de Área'), ('table', 'Tabela'), ('metric', 'Métrica/KPI')], default='bar', help_text='Tipo de visualização do bloco', max_length=20, verbose_name='Tipo de Gráfico')),
                ('x_axis_field', models.CharField(help_text="Nome do campo da query que representa o eixo X (ex: 'data', 'produto', 'mes')", max_length=100, verbose_name='Campo do Eixo X')),
                ('y_axis_fields', models.JSONField(default=list, help_text='\n        Lista de métricas para o eixo Y. Formato:\n        [\n          {"field": "total_sales", "label": "Vendas", "axis": "y1"},\n          {"field": "avg_ticket", "label": "Ticket Médio", "axis": "y2"}\n        ]\n        \n        - field: nome do campo na query\n        - label: rótulo exibido no gráfico\n        - axis: y1, y2, etc (para eixos múltiplos)\n        ', verbose_name='Campos do Eixo Y')),
                ('col_span', models.IntegerField(default=6, help_text='Largura do bloco em colunas (1-12). Grid padrão: 12 colunas', verbose_name='Largura (colunas)')),
                ('row_span', models.IntegerField(default=1, help_text='Altura do bloco em unidades de linha', verbose_name='Altura (linhas)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações adicionais (cores, legendas, tooltips, etc). Formato JSON livre', verbose_name='Configurações Extras')),
                ('ativo', models.BooleanField(default=True, help_text='Se False, o bloco não será exibido', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('datasource', models.ForeignKey(help_text='DataSource (query SQL) que alimenta este bloco', on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='dashboards.datasource', verbose_name='Fonte de Dados')),
                ('template', models.ForeignKey(help_text='Template de dashboard ao qual este bloco pertence', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboards.dashboardtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Bloco de Dashboard',
                'verbose_name_plural': 'Blocos de Dashboard',
                'ordering': ['template', 'order', 'title'],
                'indexes': [models.Index(fields=['template', 'order'], name='dashboards__templat_130a93_idx'), models.Index(fields=['template', 'ativo'], name='dashboards__templat_649298_idx')],
            },
        ),
    ]
