# Generated by Django 4.2.28 on 2026-02-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_dashboardblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardblock',
            name='x_axis_field',
            field=models.CharField(blank=True, default='', help_text="Nome do campo da query que representa o eixo X (ex: 'data', 'produto', 'mes')", max_length=100, verbose_name='Campo do Eixo X'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='y_axis_fields',
            field=models.JSONField(blank=True, default=list, help_text='\n        Lista de métricas para o eixo Y. Formato:\n        [\n          {"field": "total_sales", "label": "Vendas", "axis": "y1"},\n          {"field": "avg_ticket", "label": "Ticket Médio", "axis": "y2"}\n        ]\n        \n        - field: nome do campo na query\n        - label: rótulo exibido no gráfico\n        - axis: y1, y2, etc (para eixos múltiplos)\n        ', verbose_name='Campos do Eixo Y'),
        ),
    ]
