# Generated by Django 4.2.28 on 2026-02-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_dashboardblock_x_axis_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='series_field',
            field=models.CharField(blank=True, default='', help_text="(OPCIONAL) Nome do campo da query que define as séries do gráfico (ex: 'nome_unidade', 'produto', 'vendedor').\n        Quando configurado, o backend agrupa os dados por este campo, gerando uma série distinta para cada valor único.\n        Útil para gráficos de barras com múltiplas séries/legendas.\n        Se não configurado, o gráfico terá uma única série.", max_length=100, verbose_name='Campo de Série/Legenda'),
        ),
    ]
