# Generated by Django 4.2.28 on 2026-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_dashboardblock_series_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='contract_validated',
            field=models.BooleanField(default=False, editable=False, help_text='Indica se o contrato semântico foi validado com sucesso', verbose_name='Contrato Validado'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='detected_columns',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Colunas extraídas automaticamente da query SQL (preenchido automaticamente)', verbose_name='Colunas Detectadas'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_validation_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Data/hora da última validação bem-sucedida da query', null=True, verbose_name='Última Validação'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_validation_error',
            field=models.TextField(blank=True, editable=False, help_text='Mensagem do último erro de validação (se houver)', verbose_name='Último Erro de Validação'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='metric_date_column',
            field=models.CharField(blank=True, help_text='Campo temporal obrigatório (ex: data_venda, created_at, mes_ano)', max_length=100, verbose_name='Coluna de Data/Tempo'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='metric_value_column',
            field=models.CharField(blank=True, help_text='Campo numérico obrigatório (ex: total_vendas, quantidade, receita)', max_length=100, verbose_name='Coluna de Valor Métrico'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='series_key_column',
            field=models.CharField(blank=True, help_text='Campo categórico opcional para legendas (ex: produto, vendedor, unidade)', max_length=100, verbose_name='Coluna de Série/Legenda'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='unit_id_column',
            field=models.CharField(blank=True, help_text='Campo identificador opcional (ex: unidade_id, cod_unidade)', max_length=100, verbose_name='Coluna de ID da Unidade'),
        ),
    ]
