# Generated by Django 4.2.28 on 2026-02-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_datasource_contract_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='x_axis_granularity',
            field=models.CharField(blank=True, default='', help_text='\n        (OPCIONAL - Semantic Layer)\n        Se x_axis_field for um campo DATETIME, especifica a granularidade temporal:\n        - hour: agrupa por hora\n        - day: agrupa por dia\n        - week: agrupa por semana\n        - month: agrupa por mês\n        - quarter: agrupa por trimestre\n        - year: agrupa por ano\n        \n        Se não especificado, usa o valor bruto do campo.\n        Requer que DataSource tenha columns_metadata configurado.\n        ', max_length=20, verbose_name='Granularidade do Eixo X'),
        ),
        migrations.AddField(
            model_name='dashboardblock',
            name='y_axis_aggregations',
            field=models.JSONField(blank=True, default=list, help_text='\n        (RECOMENDADO - Semantic Layer)\n        Lista de agregações analíticas. Formato:\n        [\n          {\n            "field": "valor_venda",\n            "aggregation": "sum",\n            "label": "Total de Vendas",\n            "axis": "y1"\n          },\n          {\n            "field": "valor_venda",\n            "aggregation": "avg",\n            "label": "Ticket Médio",\n            "axis": "y2"\n          }\n        ]\n        \n        Agregações disponíveis:\n        - sum: soma dos valores\n        - avg: média dos valores\n        - count: contagem de registros\n        - count_distinct: contagem de valores únicos\n        - min: valor mínimo\n        - max: valor máximo\n        - median: mediana dos valores\n        \n        Se preenchido, QueryBuilder é usado para gerar SQL dinamicamente.\n        Se vazio, usa y_axis_fields legacy (SQL direto do DataSource).\n        ', verbose_name='Agregações do Eixo Y (Semantic Layer)'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='columns_metadata',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Metadados completos de cada coluna extraídos automaticamente. Inclui: nome, tipo no banco, tipo semântico (datetime/measure/dimension), agregações permitidas, granularidades temporais.', verbose_name='Metadados das Colunas'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='y_axis_fields',
            field=models.JSONField(blank=True, default=list, help_text='\n        [LEGACY - Mantido para compatibilidade]\n        Lista de métricas para o eixo Y. Formato:\n        [\n          {"field": "total_sales", "label": "Vendas", "axis": "y1"},\n          {"field": "avg_ticket", "label": "Ticket Médio", "axis": "y2"}\n        ]\n        \n        - field: nome do campo na query\n        - label: rótulo exibido no gráfico\n        - axis: y1, y2, etc (para eixos múltiplos)\n        \n        NOVO: Use "y_axis_aggregations" para especificar agregações semânticas.\n        ', verbose_name='Campos do Eixo Y (LEGACY)'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='detected_columns',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='LEGACY: Use columns_metadata. Lista simples de nomes de colunas.', verbose_name='Colunas Detectadas (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='nome',
            field=models.CharField(help_text="Nome único para identificar o dataset (ex: 'Sales Data', 'Customer Events')", max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='sql',
            field=models.TextField(help_text='Query SQL SIMPLES do dataset base. Use SELECT * FROM table ou view limpa. NÃO inclua agregações (SUM, COUNT), GROUP BY ou filtros analíticos. Exemplo: SELECT * FROM sales ou SELECT order_date, customer_id, amount FROM orders', verbose_name='Query SQL Base'),
        ),
    ]
