# Generated by Django 4.2.28 on 2026-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_dashboardblock_x_axis_granularity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardblock',
            name='y_axis_fields',
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='series_field',
            field=models.CharField(blank=True, default='', help_text="\n        (OPCIONAL) Campo do DataSource para agrupar séries/legendas (ex: 'unidade', 'produto', 'vendedor').\n        Gera uma série distinta para cada valor único do campo.\n        ", max_length=100, verbose_name='Campo de Série/Legenda'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='x_axis_field',
            field=models.CharField(blank=True, default='', help_text="Nome do campo do DataSource para o eixo X (ex: 'data_venda', 'produto', 'mes')", max_length=100, verbose_name='Campo do Eixo X'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='x_axis_granularity',
            field=models.CharField(blank=True, default='', help_text='\n        (OPCIONAL) Se x_axis_field for DATETIME, especifica a granularidade temporal:\n        - hour: agrupa por hora\n        - day: agrupa por dia\n        - week: agrupa por semana\n        - month: agrupa por mês\n        - quarter: agrupa por trimestre\n        - year: agrupa por ano\n        \n        Se não especificado, usa o valor bruto do campo.\n        ', max_length=20, verbose_name='Granularidade do Eixo X'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='y_axis_aggregations',
            field=models.JSONField(blank=True, default=list, help_text='\n        Lista de agregações analíticas. Formato:\n        [\n          {\n            "field": "valor_venda",\n            "aggregation": "sum",\n            "label": "Total de Vendas",\n            "axis": "y1"\n          },\n          {\n            "field": "valor_venda",\n            "aggregation": "avg",\n            "label": "Ticket Médio",\n            "axis": "y2"\n          }\n        ]\n        \n        Agregações disponíveis:\n        - sum: soma dos valores\n        - avg: média dos valores\n        - count: contagem de registros\n        - count_distinct: contagem de valores únicos\n        - min: valor mínimo\n        - max: valor máximo\n        - median: mediana dos valores\n        \n        O QueryBuilder gera SQL dinamicamente baseado nessas configurações.\n        ', verbose_name='Agregações do Eixo Y'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='detected_columns',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Lista simples de nomes de colunas. Para metadata completa, use columns_metadata.', verbose_name='Colunas Detectadas'),
        ),
    ]
