# Generated by Django 4.2.28 on 2026-02-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_remove_legacy_y_axis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtemplate',
            name='filterable_fields',
            field=models.JSONField(blank=True, help_text='Configuração de filtros dinâmicos. Exemplo: {"temporal": {"field": "sold_at", "label": "Data da Venda"}, "categorical": [{"field": "seller_id", "label": "Vendedor"}]}', null=True, verbose_name='Campos Filtráveis'),
        ),
    ]
