# Generated by Django 4.2.28 on 2026-02-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_add_filterable_fields_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='block_filter',
            field=models.TextField(blank=True, default='', help_text='Filtro WHERE específico deste bloco (ex: "status = \'cancelado\' AND payment_method = \'PIX\'").\n        Permite criar blocos diferentes da mesma fonte de dados sem duplicar o DataSource.\n        Este filtro é combinado (AND) com filtros dinâmicos e filtros da instância.', verbose_name='Filtro SQL do Bloco'),
        ),
        migrations.AddField(
            model_name='dashboardblock',
            name='metric_decimal_places',
            field=models.IntegerField(blank=True, default=0, help_text='Número de casas decimais para exibir (0-10). Usado apenas em gráficos tipo Métrica/KPI.', null=True, verbose_name='Casas Decimais'),
        ),
        migrations.AddField(
            model_name='dashboardblock',
            name='metric_prefix',
            field=models.CharField(blank=True, default='', help_text="Texto exibido antes do valor (ex: 'R$ ', 'Total: '). Usado apenas em gráficos tipo Métrica/KPI.", max_length=20, verbose_name='Prefixo da Métrica'),
        ),
        migrations.AddField(
            model_name='dashboardblock',
            name='metric_suffix',
            field=models.CharField(blank=True, default='', help_text="Texto exibido depois do valor (ex: '%', ' vendas', ' clientes'). Usado apenas em gráficos tipo Métrica/KPI.", max_length=20, verbose_name='Sufixo da Métrica'),
        ),
    ]
