# Generated by Django 4.2.28 on 2026-02-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_dashboardblock_block_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='is_draft',
            field=models.BooleanField(default=True, help_text="Se True, o bloco está em construção e pode ter configurações incompletas. Marque como 'Pronto' quando finalizar a configuração.", verbose_name='Rascunho'),
        ),
    ]
