# Generated by Django 4.2.28 on 2026-02-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_dashboardblock_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardblock',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Gráfico de Barras Verticais'), ('barh', 'Gráfico de Barras Horizontais'), ('line', 'Gráfico de Linhas'), ('pie', 'Gráfico de Pizza'), ('area', 'Gráfico de Área'), ('table', 'Tabela'), ('metric', 'Métrica/KPI')], default='bar', help_text='Tipo de visualização do bloco', max_length=20, verbose_name='Tipo de Gráfico'),
        ),
    ]
