# Generated by Django 4.2.28 on 2026-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_dashboardblock_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='block_order_by',
            field=models.CharField(blank=True, default='', help_text='Campos para ORDER BY (ex: "total_vendas DESC" ou "data_venda, unidade_id").\n        Você pode inserir 1 ou mais campos separados por vírgula.\n        Exemplo: "total_vendas DESC, data_venda ASC', max_length=500, verbose_name='Ordenação do Bloco'),
        ),
    ]
