# Generated by Django 4.2.28 on 2026-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_add_block_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardblock',
            name='series_label',
            field=models.CharField(blank=True, default='', help_text="\n        (OPCIONAL) Nome amigável para exibir no lugar do nome do campo.\n        Ex: se series_field = 'seller_name', pode definir series_label = 'Vendedor'.\n        Para TABELA: define o título da coluna de agrupamento.\n        Se não especificado, usa o nome do campo (series_field).\n        ", max_length=100, verbose_name='Label da Série/Legenda'),
        ),
        migrations.AlterField(
            model_name='dashboardblock',
            name='series_field',
            field=models.CharField(blank=True, default='', help_text="\n        (OPCIONAL) Campo do DataSource para agrupar séries/legendas (ex: 'unidade', 'produto', 'vendedor').\n        Gera uma série distinta para cada valor único do campo.\n        Para TABELA: define a coluna de agrupamento (linhas da tabela).\n        ", max_length=100, verbose_name='Campo de Série/Legenda'),
        ),
    ]
