# Generated by Django 4.2.28 on 2026-02-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_add_series_label_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatecomponent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatecomponent',
            name='component_type',
        ),
        migrations.RemoveField(
            model_name='templatecomponent',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='templatecomponent',
            name='template',
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
        migrations.DeleteModel(
            name='TemplateComponent',
        ),
    ]
